/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_devilist_glrender_pngrender_PngPreviewController0 */

#ifndef _Included_com_devilist_glrender_pngrender_PngPreviewController0
#define _Included_com_devilist_glrender_pngrender_PngPreviewController0
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_devilist_glrender_pngrender_PngPreviewController0
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_devilist_glrender_pngrender_PngPreviewController0_init
		(JNIEnv *, jobject, jstring);

/*
 * Class:     com_devilist_glrender_pngrender_PngPreviewController0
 * Method:    setSurface
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT
void JNICALL Java_com_devilist_glrender_pngrender_PngPreviewController0_setSurface
		(JNIEnv *, jobject, jobject);;

/*
 * Class:     com_devilist_glrender_pngrender_PngPreviewController0
 * Method:    resetSize
 * Signature: (II)V
 */
JNIEXPORT
void JNICALL Java_com_devilist_glrender_pngrender_PngPreviewController0_resetSize
		(JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_devilist_glrender_pngrender_PngPreviewController0
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT
void JNICALL Java_com_devilist_glrender_pngrender_PngPreviewController0_stop
		(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
